### ISSUE TITLE
Возможность указать какие поля нужны в выдаче

### ISSUE THREAD

**Issue by apilab-ru** [mdwitr0/kinopoiskdev_v1#1]
**Описание функции**
Я бы хотел, чтобы можно было указать, какие поля нужны в выдаче)

**Пояснение**
В моём случае использования ([для расширения](https://chrome.google.com/webstore/detail/watchlist/poiackckjbminlmppejhfkmjkfpfegkd))  мне нужны ещё жанры (которых в базовой выдаче нет), и при этом не нужны watchability, votes 

**Предложенное решение**
Дать возможность передать список полей, которые нужны.
Или альтернативно, добавить жанры в базовую выдачу.

**Метки (необязательно)**
"фильтры", "api"

**Comment by mdwitr0** [comment]
<img width="1553" alt="Screenshot 2023-02-18 at 6 12 26 PM" src="https://user-images.githubusercontent.com/109113769/219879024-57c53e5d-e8a8-452e-9ff0-15d4e45d4cfa.png">

Если я вас правильно понял, то этот функционал уже есть. На скриншот пример использования параметра selectFields, который указывает, какие поля должны быть возвращены. 
Сюда можно передать любые поля доступные в модели

**Comment by apilab-ru** [comment]
точно, не внимательно доку смотрел, спасибо)
